---
spring:

  application:
    name: springCloudApp
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
db:
  mysql:
    minIdle: 20
    password: 123456
    maxLifetimeMs: 1800000
    connectionTimeoutMs: 30000
    connectionTestQuery: SELECT 1
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    idleTimeoutMs: 600000
    transactionTimeoutS: 30
    maxPoolSize: 20
    username: root
